# -*- coding: utf-8 -*-
"""Student Performance Factors.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TX6m5fiKnuPnB1msqtvvPaGTmSW42MEF

# Student Performance Factors
"""

import pandas as pd
import numpy as np

from bokeh.io import output_notebook
from bokeh.plotting import figure, show

#@title Loading data

LoadCsv = 'https://raw.githubusercontent.com/Ashraful332/Scikit-learn/main/data/SPF/StudentPerformanceFactors.csv'
data = pd.read_csv(LoadCsv)
data.head()

"""## Graph"""

output_notebook()

#@title Basic Graph
p = figure(width=400, height=400)

# add a scatter circle renderer with a size, color, and alpha
p.scatter([1, 2, 3, 4, 5], [6, 7, 2, 4, 5], size=20, color="navy", alpha=0.5)

# show the results
show(p)

#@title Hours_Studied to Exam_Score

p = figure(title="My Beautiful Bokeh Graph",width=400, height=400)

p.scatter(data['Hours_Studied'], data['Exam_Score'], size=20, color="navy", alpha=0.5)

p.xaxis.axis_label = "Hours_Studied"
p.yaxis.axis_label = "Exam Score"

show(p)

