# -*- coding: utf-8 -*-
"""Student Performance Factors.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TX6m5fiKnuPnB1msqtvvPaGTmSW42MEF

# Student Performance Factors
"""

import pandas as pd
import numpy as np

from bokeh.io import output_notebook
from bokeh.plotting import figure, show
import joblib

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

#@title Loading data

LoadCsv = 'https://raw.githubusercontent.com/Ashraful332/Scikit-learn/main/data/SPF/StudentPerformanceFactors.csv'
data = pd.read_csv(LoadCsv)
data.head()

"""## Graph"""

output_notebook()

#@title Basic Graph
p = figure(width=400, height=400)

# add a scatter circle renderer with a size, color, and alpha
p.scatter([1, 2, 3, 4, 5], [6, 7, 2, 4, 5], size=20, color="navy", alpha=0.5)

# show the results
show(p)

#@title Hours_Studied to Exam_Score

p = figure(title="Hours Studied vs Exam Score",width=400, height=400)

p.scatter(data['Hours_Studied'], data['Exam_Score'], size=20, color="navy", alpha=0.5)

p.xaxis.axis_label = "Hours_Studied"
p.yaxis.axis_label = "Exam Score"

show(p)

#@title Attendance vs Exam_Score
p = figure(title="Attendance vs Exam Score",width=400, height=400)

p.scatter(data['Attendance'], data['Exam_Score'], size=20, color="navy", alpha=0.5)

p.xaxis.axis_label = "Attendance"
p.yaxis.axis_label = "Exam Score"

show(p)

Family_Income = data['Family_Income'].unique()
Exam_Score = data['Exam_Score']

p = figure(x_range=Family_Income, height=350, title="Family Income vs Exam Score",
           toolbar_location=None, tools="")

p.vbar(x=Family_Income, top=Exam_Score, width=0.9)

p.xgrid.grid_line_color = None
p.y_range.start = 0

p.xaxis.axis_label = "Family Income"
p.yaxis.axis_label = "Exam Score"

show(p)

#@title Sleep_Hours vs Exam Score
p = figure(title="Sleep Hours vs Exam Score",width=400, height=400)

p.scatter(data['Sleep_Hours'], data['Exam_Score'], size=20, color="navy", alpha=0.5)

p.xaxis.axis_label = "Sleep_Hours"
p.yaxis.axis_label = "Exam Score"

show(p)

"""# Train Model"""

data = pd.read_csv(LoadCsv)
data.head()

# convert Parental_Involvement Low Medium High into 0 1 2
data['Parental_Involvement'] = data['Parental_Involvement'].map({
    "Low":0,
    "Medium":1,
    "High":2
})

data['Parental_Involvement'].head()

# convert Access_to_Resources Low Medium High into 0 1 2
data['Access_to_Resources'] = data['Access_to_Resources'].map({
    "Low":0,
    "Medium":1,
    "High":2
})
data['Access_to_Resources'].head()

# convert Extracurricular_Activities Yes/No into 1/0
data["Extracurricular_Activities"] = data["Extracurricular_Activities"].map({
    "No": 0,
    "Yes": 1
})
data["Extracurricular_Activities"].head()

# convert Motivation_Level Low Medium High into 0 1 2
data['Motivation_Level'] = data['Motivation_Level'].map({
    "Low":0,
    "Medium":1,
    "High":2
})
data['Motivation_Level'].head()

# convert Internet_Access Yes/No into 1/0
data["Internet_Access"] = data["Internet_Access"].map({
    "No": 0,
    "Yes": 1
})
data["Internet_Access"].head()

# convert Family_Income Low Medium High into 0 1 2
data['Family_Income'] = data['Family_Income'].map({
    "Low":0,
    "Medium":1,
    "High":2
})
data['Family_Income'].head()

# convert Teacher_Quality Low Medium High into 0 1 2
data['Teacher_Quality'] = data['Teacher_Quality'].map({
    "Low":0,
    "Medium":1,
    "High":2
}).astype('Int64')
data['Teacher_Quality'].head()

# convert School_Type Public/Private into 1/0
data["School_Type"] = data["School_Type"].map({
    "Public": 0,
    "Private": 1
})
data["School_Type"].head()

# convert Peer_Influence Low Medium High into 0 1 2
data['Peer_Influence'] = data['Peer_Influence'].map({
    "Negative":0,
    "Positive":1,
    "Neutral":2
})
data['Peer_Influence'].head()

# convert Learning_Disabilities Yes/No into 1/0
data["Learning_Disabilities"] = data["Learning_Disabilities"].map({
    "No": 0,
    "Yes": 1
})
data["Learning_Disabilities"].head()

# convert Parental_Education_Level Low Medium High into 0 1 2
data['Parental_Education_Level'] = data['Parental_Education_Level'].map({
    "High School":0,
    "College":1,
    "Postgraduate":2
}).astype('Int64')
data['Parental_Education_Level'].head()

# convert Distance_from_Home Low Medium High into 0 1 2
data['Distance_from_Home'] = data['Distance_from_Home'].map({
    "Near":0,
    "Moderate":1,
    "Far":2
}).astype('Int64')
data['Distance_from_Home'].head()

# convert Gender Yes/No into 1/0
data["Gender"] = data["Gender"].map({
    "Male": 0,
    "Female": 1
})
data["Gender"].head()

"""## Training Model"""

data['Exam_Score']

# @title Working Simple code

# Drop rows with any NaN values
data.dropna(inplace=True)

# Features
X = data[[
    "Hours_Studied",	"Attendance",	"Parental_Involvement",	"Access_to_Resources",	"Extracurricular_Activities",
    "Sleep_Hours",	"Previous_Scores",	"Motivation_Level",	"Internet_Access",	"Tutoring_Sessions",	"Family_Income",
    "Teacher_Quality",	"School_Type",	"Peer_Influence",	"Physical_Activity",	"Learning_Disabilities",
    "Parental_Education_Level",	"Distance_from_Home",	"Gender"
]]

# Target
y = data['Exam_Score']

# Split Data
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Set Model
model = LinearRegression()

# Train Model
model.fit(X_train, y_train)

print("Training Complete!")

# =========================
# SAVE MODEL
# =========================

joblib.dump(model, "student_placement_model.pkl")

print("Model saved!")

"""# Predict Model"""

data.head()

# Load Save Model
def load_model(model_path):
    model = joblib.load(model_path)
    print("Model loaded!")
    return model
# load_model("student_placement_model.pkl")



# Predict new student placement
# The input array had 20 features, but the model expects 19.
# Removed the leading '0' to match the 19 features: Hours_Studied, Attendance, Parental_Involvement, Access_to_Resources, Extracurricular_Activities, Sleep_Hours, Previous_Scores, Motivation_Level, Internet_Access, Tutoring_Sessions, Family_Income, Teacher_Quality, School_Type, Peer_Influence, Physical_Activity, Learning_Disabilities, Parental_Education_Level, Distance_from_Home, Gender.
result = model.predict([[
    23,	84,	0,	2,	0,	7,	73,	0,	1,	0,	0,	1,	0,	1,	3,	0,	0,	0,	0
]])

print("Prediction:", result)

"""## Predict Model with test.csv file"""

#@title Loading test data

LoadTrainCsv = 'https://raw.githubusercontent.com/Ashraful332/Scikit-learn/main/data/SPF/test.csv'
TrainData = pd.read_csv(LoadTrainCsv)
TrainData.head()

#@title Convert string TrainData into number

# convert Parental_Involvement Low Medium High into 0 1 2
TrainData['Parental_Involvement'] = TrainData['Parental_Involvement'].map({
    "Low":0,
    "Medium":1,
    "High":2
})

TrainData['Parental_Involvement'].head()

# convert Access_to_Resources Low Medium High into 0 1 2
TrainData['Access_to_Resources'] = TrainData['Access_to_Resources'].map({
    "Low":0,
    "Medium":1,
    "High":2
})
TrainData['Access_to_Resources'].head()

# convert Extracurricular_Activities Yes/No into 1/0
TrainData["Extracurricular_Activities"] = TrainData["Extracurricular_Activities"].map({
    "No": 0,
    "Yes": 1
})
TrainData["Extracurricular_Activities"].head()

# convert Motivation_Level Low Medium High into 0 1 2
TrainData['Motivation_Level'] = TrainData['Motivation_Level'].map({
    "Low":0,
    "Medium":1,
    "High":2
})
TrainData['Motivation_Level'].head()

# convert Internet_Access Yes/No into 1/0
TrainData["Internet_Access"] = TrainData["Internet_Access"].map({
    "No": 0,
    "Yes": 1
})
TrainData["Internet_Access"].head()

# convert Family_Income Low Medium High into 0 1 2
TrainData['Family_Income'] = TrainData['Family_Income'].map({
    "Low":0,
    "Medium":1,
    "High":2
})
TrainData['Family_Income'].head()

# convert Teacher_Quality Low Medium High into 0 1 2
TrainData['Teacher_Quality'] = TrainData['Teacher_Quality'].map({
    "Low":0,
    "Medium":1,
    "High":2
}).astype('Int64')
TrainData['Teacher_Quality'].head()

# convert School_Type Public/Private into 1/0
TrainData["School_Type"] = TrainData["School_Type"].map({
    "Public": 0,
    "Private": 1
})
TrainData["School_Type"].head()

# convert Peer_Influence Low Medium High into 0 1 2
TrainData['Peer_Influence'] = TrainData['Peer_Influence'].map({
    "Negative":0,
    "Positive":1,
    "Neutral":2
})
TrainData['Peer_Influence'].head()

# convert Learning_Disabilities Yes/No into 1/0
TrainData["Learning_Disabilities"] = TrainData["Learning_Disabilities"].map({
    "No": 0,
    "Yes": 1
})
TrainData["Learning_Disabilities"].head()

# convert Parental_Education_Level Low Medium High into 0 1 2
TrainData['Parental_Education_Level'] = TrainData['Parental_Education_Level'].map({
    "High School":0,
    "College":1,
    "Postgraduate":2
}).astype('Int64')
TrainData['Parental_Education_Level'].head()

# convert Distance_from_Home Low Medium High into 0 1 2
TrainData['Distance_from_Home'] = TrainData['Distance_from_Home'].map({
    "Near":0,
    "Moderate":1,
    "Far":2
}).astype('Int64')
TrainData['Distance_from_Home'].head()

# convert Gender Yes/No into 1/0
TrainData["Gender"] = TrainData["Gender"].map({
    "Male": 0,
    "Female": 1
})
TrainData["Gender"].head()

# Replaces NaNs as 0
TrainData['Exam_Score'] = TrainData['Exam_Score'].fillna(0).astype('Int64')

TrainData.head()

#@title Test CSV file

# Load model
model = joblib.load("student_placement_model.pkl")

test_data = TrainData

# Drop rows with any NaN values to handle potential NaNs introduced during mapping
test_data.dropna(inplace=True)

# 3. Separate feature columns from the target column
X_test = test_data.drop(columns=["Exam_Score"])

# 4. Generate predictions
predicted_scores = model.predict(X_test)

# 5. Fill the Exam_Score column with the model's predictions
test_data["Exam_Score"] = predicted_scores

# 6. Export the updated dataset to a new CSV file
test_data.to_csv("test_with_predictions.csv", index=False)

print("Predictions filled and saved to 'test_with_predictions.csv'")